@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

public class GrabReport {
    public static void main(String[] args)
    {
//        System.out.print("Input something: ");

//        Scanner inp = new Scanner(System.in);
//        String aLine = inp.nextLine();
//        System.out.printf("%n%20s%n", aLine);
//
//        System.out.println("ura ho");
//        String fReport = report();
//        System.out.println(fReport);
//        System.out.printf("%n%,20.4f%n", 12345.678);

        //System.out.printf("here's your food sir %s", content);

        //query returns data from api, jsonparser then converts into a more useful format
        String content = query();
        String parsed = jsonParser(content);
    }
    private static String report()
    {
        String response = "cake";
        return response;
    }

    private static String query() {

        //Method 1 (inefficient)
        BufferedReader reader; //reads everything from the website
        String line; //variable to temporarily hold each line
        StringBuffer responseContent = new StringBuffer(); //appends each line to the response

        HttpURLConnection connection = null;
        try {
            URL url = new URL("https://world.openfoodfacts.org/api/v0/product/0858133006877.json");
            connection = (HttpURLConnection) url.openConnection();

            //request setup
            connection.setRequestMethod("GET");
            connection.setConnectTimeout(5000);
            connection.setReadTimeout(5000);

            //detects if connection was successful
            int status = connection.getResponseCode();
            System.out.println(status);

            boolean error = connection.getResponseCode() > 299;
            reader = new BufferedReader(new InputStreamReader( error ? connection.getErrorStream() : connection.getInputStream()));
            while ((line = reader.readLine()) != null)
                responseContent.append(line);
            reader.close();
            //responseContent.toString(); converts the http response to a string

        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            connection.disconnect();
        }
//        //Method 2
//        HttpClient client = HttpClient.newHttpClient();
//        HttpRequest request = HttpRequest.newBuilder()
//                .uri(URI.create("https://world.openfoodfacts.org/api/v0/product/0737628064502.json"))
//                .build();
//        //a::b refers to a lambda expression (::)
//        client.sendAsync(request, HttpResponse.BodyHandlers.ofString())
//                .thenApply(HttpResponse::body)
//                .thenAccept(System.out::println)
//                .join();
//

//        //Method 3
//        HttpClient client = HttpClient.newHttpClient();
//        HttpRequest request = HttpRequest.newBuilder()
//                .uri(URI.create("https://world.openfoodfacts.org/api/v0/product/0737628064502.json"))
//                .build();
//
//        String responseContent = client.sendAsync(request, HttpResponse.BodyHandlers.ofString())
//                .thenApply(HttpResponse::body).toString();
//
//        return responseContent;

        return responseContent.toString();
    }
@enduml